# Roll A — Data Loading

In [47]:
import pandas as pd
from supabase import create_client

In [48]:
import os
from dotenv import load_dotenv

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

print("URL exists:", SUPABASE_URL is not None)
print("KEY exists:", SUPABASE_KEY is not None)

URL exists: True
KEY exists: True

In [49]:
supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

print("Supabase connected")

Supabase connected

In [50]:

# Kqigi andmete laadimine sales tabelist
all_sales = []
offset = 0
while True:
    response = supabase.table('sales').select('*').range(offset, offset + 999).execute()
    if not response.data:
        break
    all_sales.extend(response.data)
    offset += 1000

df_sales = pd.DataFrame(all_sales)
print("Sales shape:", df_sales.shape)
df_sales.head()

Sales shape: (10118, 12)

,id,sale_id,invoice_id,sale_date,customer_id,product_id,quantity,unit_price,total_price,channel,store_location,payment_method
0,1,1,INV-202301-00001,2023-01-10T00:00:00,2588.0,1274,2,234.79,469.58,pood,Tallinn,kaart
1,2,2,INV-202301-00002,2023-01-16T00:00:00,4338.0,1207,2,241.13,482.26,pood,Pärnu,järelmaks
2,3,3,INV-202301-00003,2023-01-05T00:00:00,4673.0,1264,1,258.46,221.19,pood,Pärnu,järelmaks
3,4,4,INV-202301-00004,2023-01-02T00:00:00,4677.0,1341,3,45.21,135.63,pood,Tartu,sularaha
4,5,5,INV-202301-00005,2023-01-13T00:00:00,2390.0,1284,1,99.57,99.57,pood,Tartu,kaart

In [51]:
# Kqigi andmete laadimine customers tabelist
all_customers = []
offset = 0
while True:
    response = supabase.table('customers').select('*').range(offset, offset + 999).execute()
    if not response.data:
        break
    all_customers.extend(response.data)
    offset += 1000

df_customers = pd.DataFrame(all_customers)
print("Customers shape:", df_customers.shape)
df_customers.head()

Customers shape: (3150, 9)

,customer_id,first_name,last_name,email,phone,city,registration_date,loyalty_tier,birth_year
0,2001,Eha,Aas,eha.aas@telia.ee,+372 8713 1455,Tallinn,2024-02-27,None,1973
1,2002,Aivar,Kõiv,aivar.koiv@outlook.com,+372 8943 8684,Haapsalu,2025-01-09,bronze,1988
2,2003,Maris,Rebane,maris.rebane@telia.ee,+372 5918 5726,Tartu,2021-02-03,None,1999
3,2004,Jaak,Talvik,jaak.talvik@mail.ee,+372 8554 4232,Tallinn,2023-11-12,silver,1974
4,2005,Raivo,Koppel,raivo.koppel@yahoo.com,+372 5298 4365,Tallinn,2023-05-22,bronze,2004

In [52]:
df = pd.merge(
    df_sales,
    df_customers,
    on="customer_id",
    how="left"
)

print("Merged shape:", df.shape)

df.head()

Merged shape: (10118, 20)

,id,sale_id,invoice_id,sale_date,customer_id,product_id,quantity,unit_price,total_price,channel,store_location,payment_method,first_name,last_name,email,phone,city,registration_date,loyalty_tier,birth_year
0,1,1,INV-202301-00001,2023-01-10T00:00:00,2588.0,1274,2,234.79,469.58,pood,Tallinn,kaart,Hille,Paju,None,+372 5429 0294,Tallinn,2022-07-28,bronze,1997.0
1,2,2,INV-202301-00002,2023-01-16T00:00:00,4338.0,1207,2,241.13,482.26,pood,Pärnu,järelmaks,Merle,Luik,merle.luik@mail.ee,+372 5150 1812,Tallinn,2020-09-22,None,1996.0
2,3,3,INV-202301-00003,2023-01-05T00:00:00,4673.0,1264,1,258.46,221.19,pood,Pärnu,järelmaks,Liina,Saar,liina.saar@gmail.com,+372 8809 7990,Tallinn,2020-03-31,silver,1973.0
3,4,4,INV-202301-00004,2023-01-02T00:00:00,4677.0,1341,3,45.21,135.63,pood,Tartu,sularaha,Aili,Pihl,aili.pihl@yahoo.com,+372 8375 4888,Narva,2021-10-08,gold,1972.0
4,5,5,INV-202301-00005,2023-01-13T00:00:00,2390.0,1284,1,99.57,99.57,pood,Tartu,kaart,Triin,Lill,triin.lill@telia.ee,+372 5378 0596,Tartu,2021-04-09,None,1996.0

In [53]:
print("Merged DataFrame shape:")
print(df.shape)

print("\nData types:")
print(df.dtypes)

print("\nFirst 5 rows:")
display(df.head())

Merged DataFrame shape:
(10118, 20)

Data types:
id                     int64
sale_id                int64
invoice_id            object
sale_date             object
customer_id          float64
product_id             int64
quantity               int64
unit_price           float64
total_price          float64
channel               object
store_location        object
payment_method        object
first_name            object
last_name             object
email                 object
phone                 object
city                  object
registration_date     object
loyalty_tier          object
birth_year           float64
dtype: object

First 5 rows:

,id,sale_id,invoice_id,sale_date,customer_id,product_id,quantity,unit_price,total_price,channel,store_location,payment_method,first_name,last_name,email,phone,city,registration_date,loyalty_tier,birth_year
0,1,1,INV-202301-00001,2023-01-10T00:00:00,2588.0,1274,2,234.79,469.58,pood,Tallinn,kaart,Hille,Paju,None,+372 5429 0294,Tallinn,2022-07-28,bronze,1997.0
1,2,2,INV-202301-00002,2023-01-16T00:00:00,4338.0,1207,2,241.13,482.26,pood,Pärnu,järelmaks,Merle,Luik,merle.luik@mail.ee,+372 5150 1812,Tallinn,2020-09-22,None,1996.0
2,3,3,INV-202301-00003,2023-01-05T00:00:00,4673.0,1264,1,258.46,221.19,pood,Pärnu,järelmaks,Liina,Saar,liina.saar@gmail.com,+372 8809 7990,Tallinn,2020-03-31,silver,1973.0
3,4,4,INV-202301-00004,2023-01-02T00:00:00,4677.0,1341,3,45.21,135.63,pood,Tartu,sularaha,Aili,Pihl,aili.pihl@yahoo.com,+372 8375 4888,Narva,2021-10-08,gold,1972.0
4,5,5,INV-202301-00005,2023-01-13T00:00:00,2390.0,1284,1,99.57,99.57,pood,Tartu,kaart,Triin,Lill,triin.lill@telia.ee,+372 5378 0596,Tartu,2021-04-09,None,1996.0

In [54]:
required_columns = ["customer_id", "sale_date", "total_price", "email"]

for column in required_columns:
    print(column, "exists:", column in df.columns)

customer_id exists: True
sale_date exists: True
total_price exists: True
email exists: True

# ROLL B - Data Cleaning

In [55]:
print("Initial shape:", df.shape)

Initial shape: (10118, 20)

In [56]:
print("Duplicates:", df.duplicated().sum())
df = df.drop_duplicates()
print("After removing duplicates:", df.shape)

Duplicates: 0
After removing duplicates: (10118, 20)

In [57]:
print("NULL values:\n", df.isnull().sum())

NULL values:
 id                      0
sale_id                 0
invoice_id              0
sale_date               0
customer_id           988
product_id              0
quantity                0
unit_price              0
total_price             0
channel                 0
store_location       3462
payment_method          0
first_name            988
last_name             988
email                1944
phone                 988
city                  988
registration_date     988
loyalty_tier         4660
birth_year            988
dtype: int64

In [58]:
df = df.dropna(subset=['customer_id', 'sale_date', 'total_price'])
print("After removing critical NULLs:", df.shape)

After removing critical NULLs: (9130, 20)

In [59]:
df['sale_date'] = pd.to_datetime(df['sale_date'])
print("sale_date type:", df['sale_date'].dtype)

sale_date type: datetime64[ns]

In [60]:
print("Negative total_price values:", (df['total_price'] <= 0).sum())
df = df[df['total_price'] > 0]
print("After removing outliers:", df.shape)

Negative total_price values: 180
After removing outliers: (8950, 20)

In [61]:
print("--- CLEANING REPORT ---")
print(f"Final shape: {df.shape}")
print(f"Unique customers: {df['customer_id'].nunique()}")
print(f"Date range: {df['sale_date'].min().date()} to {df['sale_date'].max().date()}")

--- CLEANING REPORT ---
Final shape: (8950, 20)
Unique customers: 2540
Date range: 2023-01-01 to 2026-06-28